/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eronalves;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name = "cc", mixinStandardHelpOptions = true, version = "cc 0.1", description = "commandline helper to create java classes")
public class App implements Callable<Integer> {

  private static final String JAVA_TEST_DIR = "src/test/java/";

  private static final String JAVA_MAIN_DIR = "src/main/java/";

  private static final String JAVA_EXTENSION = ".java";

  @Parameters(index = "0", description = "The class name")
  private String name;

  public static void main(String[] args) {
    int exitCode = new CommandLine(new App()).execute(args);
    System.exit(exitCode);
  }

  @Override
  public Integer call() throws Exception {
    String workingDirectory = System.getenv("PWD");

    Optional<String> testPathSegment = List.of(JAVA_MAIN_DIR, JAVA_TEST_DIR).stream()
        .filter(pathSegment -> workingDirectory.toString().contains(pathSegment)).findFirst();

    if (testPathSegment.isEmpty()) {
      System.out.println("Not a valid package directory");
      return 1;
    }

    String pathSegment = testPathSegment.get();
    String rawPackageDefinition = workingDirectory
        .substring(workingDirectory.indexOf(pathSegment) + pathSegment.length());

    String packageDefinition = rawPackageDefinition.replaceAll("/", ".");

    Path filePath = Files.createFile(Path.of(workingDirectory, name + JAVA_EXTENSION));
    Files.writeString(filePath, "package " + packageDefinition + ";\n\npublic class " + name + " {\n\n}");

    return 0;
  }
}
